In [1]:
ls

Nicole_100-pandas-puzzles.ipynb   assessment_1.ipynb
Nicole_100_Numpy_exercises.ipynb  rent.csv
README.md


In [2]:
import numpy as np
import pandas as pd

### Python 1

In [47]:
def max_lists(list1, list2):
    '''Compares the elements of list1, and list2 (assumed to be the same
    length),and returns the maximum value between the two, for each element.

    Parameters
    ----------
    list1, list2: list, list
        (Of the same length)

    Returns
    -------
    list
    '''
    list3 =[]
    for a,b in zip(list1, list2):
        if a>=b:
            list3.append(a)
        else:
            list3.append(b)
    return list3

In [48]:
list1 = [5,4,3,2,1]
list2 = [4,2,7,8,9]
print(max_lists(list1, list2))

[5, 4, 7, 8, 9]


In [49]:
#another solution
output = [max(i1, i2) for i1, i2 in zip(list1, list2)]
print(output)

[5, 4, 7, 8, 9]


### Python 2

In [55]:
def get_diagonal(mat):
    '''Given a matrix encoded as a 2 dimensional python list (i.e. a list of
    uniform length lists), returns a list containing all the values along the
    diagonal starting at the index 0, 0. (Assumes that the matrix is nonempty.)

    Parameters
    ----------
    mat: list of lists

    Returns
    -------
    list

    Example
    -------
    >>> mat = [[1, 2], [3, 4], [5, 6]]
    >>> get_diagonal(mat)
    [1, 4]
    '''
    mat =np.array(mat)
    return list(mat.diagonal())

In [56]:
mat = [[1, 2], [3, 4], [5, 6]]
print(get_diagonal(mat))

[1, 4]


In [57]:
#another solution
print([mat[i][i] for i in range(min(len(mat), len(mat[0])))])

[1, 4]


In [62]:
# test
mat2 =  [[1, 2, 3, 4], [3, 4, 5,6], [5, 6, 7,8]]
print(np.array(mat2),'\n')
print(get_diagonal(mat2),'\n')
print([mat2[i][i] for i in range(min(len(mat2), len(mat2[0])))])



[[1 2 3 4]
 [3 4 5 6]
 [5 6 7 8]] 

[1, 4, 7] 

[1, 4, 7]


### Python 3

In [64]:
def merge_dictionaries(d1, d2):
    '''
    INPUT: dictionary, dictionary
    OUTPUT: dictionary

    Return a new dictionary which contains all the keys from d1 and d2 with
    their associated values. If a key is in both dictionaries, the value should
    be the sum of the two values.
    '''
    d = d1.copy()
    for key, value in d2.items():
        d[key] = d.get(key, 0) + value
    return d

In [65]:
d1 = {'a':1, 'b':2, 'c':3}
d2 = {'d':1, 'b':2, 'c':3}
print(merge_dictionaries(d1, d2))

{'a': 1, 'b': 4, 'c': 6, 'd': 1}


In [70]:
#test get function
print(d1.get('d',0))
print(d1.get('d'))

0
None


### Python/Linear Algebra


In [82]:
def matrix_multiplication(A, B):
    '''Return the matrix which is the product of matrix A and matrix B
    where A and B will be (a) integer valued (b) square matrices
    (c) of size n-by-n (d) encoded as lists of lists,  e.g.
    A = [[2, 3, 4], [6, 4, 2], [-1, 2, 0]] corresponds to the matrix
    | 2  3  4 |
    | 6  4  2 |
    |-1  2  0 |

    YOU MAY NOT USE NUMPY. Write your solution in straight python.

    Parameters
    ----------
    a, b: list of lists of integers, list of lists integers
        All inner/outer lists are of length n, so as to construct square
        matrices.

    Returns
    -------
    list of lists of integers
        The product of a matrix multiplication operation.
    '''
    n = len(A)
    result = []
    # iterate over the rows of A
    for i in range(n):
        row = []
        # iterate over the columns of B
        for j in range(n):
            total = 0
            # iterate ith row of A with jth column of B dot product
            for k in range(n):
                # k implements [ith row][jth column] element-wise dot product
                total += A[i][k] * B[k][j]
            # column j of row i
            row.append(total)
        # all columns j of row i completed
        result.append(row)
    # all rows done
    return result



In [85]:
A = [[2, 3, 4], [6, 4, 2], [-1, 2, 0]]
B = [[4, 3, 4], [6, 4, 2], [-1, 2, 0]]
ma=np.array(A)
mb=np.array(B)
print("A:\n",ma,'\n')
print("B:\n",mb,'\n')
print("A product b:\n",ma.dot(mb),'\n')
print("call function:\n", matrix_multiplication(A, B))

A:
 [[ 2  3  4]
 [ 6  4  2]
 [-1  2  0]] 

B:
 [[ 4  3  4]
 [ 6  4  2]
 [-1  2  0]] 

A product b:
 [[22 26 14]
 [46 38 32]
 [ 8  5  0]] 

call function:
 [[22, 26, 14], [46, 38, 32], [8, 5, 0]]


### Pandas Challenges1

In [5]:
df = pd.read_csv('rent.csv')
df.head(10)

Neighborhood         City State  med_2011  med_2014
0       Northeast Dallas       Dallas    TX     825.0     985.0
1               Paradise    Las Vegas    NV     900.0    1100.0
2               Maryvale      Phoenix    AZ     795.0     850.0
3        Upper West Side     New York    NY    2795.0    3300.0
4      South Los Angeles  Los Angeles    CA    1150.0    1400.0
5           Sherman Oaks  Los Angeles    CA    1399.0    1450.0
6        Upper East Side     New York    NY    2250.0    2700.0
7          Sunrise Manor    Las Vegas    NV     800.0     895.0
8          East New York     New York    NY    1350.0    1500.0
9  Southeast Los Angeles  Los Angeles    CA    1200.0    1300.0

In [11]:
def pandas_add_increase_column(df):
    df['Increase'] = df['med_2014'] -df['med_2011']
    
    

In [17]:
pandas_add_increase_column(df)
df.head(10)

Neighborhood         City State  med_2011  med_2014  Increase
0       Northeast Dallas       Dallas    TX     825.0     985.0     160.0
1               Paradise    Las Vegas    NV     900.0    1100.0     200.0
2               Maryvale      Phoenix    AZ     795.0     850.0      55.0
3        Upper West Side     New York    NY    2795.0    3300.0     505.0
4      South Los Angeles  Los Angeles    CA    1150.0    1400.0     250.0
5           Sherman Oaks  Los Angeles    CA    1399.0    1450.0      51.0
6        Upper East Side     New York    NY    2250.0    2700.0     450.0
7          Sunrise Manor    Las Vegas    NV     800.0     895.0      95.0
8          East New York     New York    NY    1350.0    1500.0     150.0
9  Southeast Los Angeles  Los Angeles    CA    1200.0    1300.0     100.0

### Pandas Challenges2

In [30]:
def pandas_max_rent(df):
    grouped = df.groupby(['City','State'])
    return grouped['City', 'State', 'med_2011', 'med_2014'].max()

In [44]:
df2 = pandas_max_rent(df)
df2.head(10)

/Users/nicochen/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  This is separate from the ipykernel package so we can avoid doing imports until


City State  med_2011  med_2014
City        State                                       
Akron       OH           Akron    OH     690.0     725.0
Albany      NY          Albany    NY       NaN     952.0
Albuquerque NM     Albuquerque    NM    1099.0    1150.0
Alexandria  VA      Alexandria    VA    2155.0    2250.0
Amherst     MA         Amherst    MA       NaN       NaN
Anaheim     CA         Anaheim    CA    2005.0    2245.0
Anchorage   AK       Anchorage    AK       NaN    1995.0
Arlington   TX       Arlington    TX    1100.0    1300.0
            VA       Arlington    VA    2800.0    2796.0
Atlanta     GA         Atlanta    GA    2000.0    2450.0

In [45]:
#another solution
df3 = df.groupby(['City', 'State']).max().reset_index()[['City', 'State', 'med_2011','med_2014']]
df3.head(10)

City State  med_2011  med_2014
0        Akron    OH     690.0     725.0
1       Albany    NY       NaN     952.0
2  Albuquerque    NM    1099.0    1150.0
3   Alexandria    VA    2155.0    2250.0
4      Amherst    MA       NaN       NaN
5      Anaheim    CA    2005.0    2245.0
6    Anchorage    AK       NaN    1995.0
7    Arlington    TX    1100.0    1300.0
8    Arlington    VA    2800.0    2796.0
9      Atlanta    GA    2000.0    2450.0